from models.consultaModel import Consulta

class consultaCRUD:
    def __init__(self, conexao):
        self.conn = conexao
        self.cursor = self.conn.cursor()

    def criarTabelaConsulta(self):
        self.cursor.execute("""
            CREATE TABLE consultas (
                id NUMBER (8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                paciente_id NUMBER (8) REFERENCES pacientes(id),
                data DATE NOT NULL,
                hora VARCHAR2(5) NOT NULL,
                especialidade VARCHAR2(100) NOT NULL
            )
        """)
        self.conn.commit()

    def criarConsulta(self, consulta: Consulta):
        sql = "INSERT INTO consultas (paciente_id, data, hora, especialidade) VALUES (:1, :2, :3, :4)"
        self.cursor.execute(sql, (consulta.paciente_id, consulta.data, consulta.hora, consulta.especialidade))
        self.conn.commit()

    def listarConsultas(self):
        self.cursor.execute("SELECT id, paciente_id, data, hora, especialidade FROM consultas")
        rows = self.cursor.fetchall()
        return [Consulta(id=row[0], paciente_id=row[1], data=row[2], hora=row[3], especialidade=row[4]) for row in rows]
    
    def atualizarConsulta(self, idConsulta, novaData, novoHorario):
        sql = "UPDATE consultas SET data = :1, hora = :2 WHERE id = :3"
        self.cursor.execute(sql, (novaData, novoHorario, idConsulta))
        self.conn.commit()

    def deletarConsulta(self, idConsulta):
        sql = "DELETE FROM consultas WHERE id = :1"
        self.cursor.execute(sql, (idConsulta,))
        self.conn.commit()
        