from models.pacienteModel import Paciente
from dataBase.conexao.db_manager import DBManager

class pacienteCRUD:
    def __init__(self, conexao):
        self.conn = conexao
        self.cursor = self.conn.cursor()

    def criarTabelaPaciente(self):
        self.cursor.execute("""
            SELECT table_name
            FROM user_tables
            WHERE table_name = 'PACIENTE'
        """)
        tabela = self.cursor.fetchone()

        if tabela:
            print("Tabela 'PACIENTE' já existe.")
        else:
            self.cursor.execute("""
                CREATE TABLE PACIENTE (
                    id NUMBER (8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR2(100) NOT NULL,
                    idade NUMBER (3) NOT NULL,
                    cpf VARCHAR2(20) NOT NULL,
                    email VARCHAR2(100) NOT NULL,
                    senha VARCHAR2(20) NOT NULL
                )
            """)
        self.conn.commit()

    def buscarPorCPF(self, cpf):
        self.cursor.execute("SELECT id, nome, idade, cpf, email, senha, cep FROM PACIENTE WHERE cpf = :cpf", {"cpf": cpf})
        row = self.cursor.fetchone()

        if row:
            return Paciente(id=row[0], nome=row[1], idade=row[2], CPF=row[3], email=row[4], senha=row[5], CEP=row[6])
        else:
            return None

    def criarPaciente (self, paciente: Paciente):
        sql = "INSERT INTO PACIENTE (nome, idade, cpf, email, senha, cep) VALUES ( :1, :2, :3, :4, :5, :6)"
        self.cursor.execute(sql, (paciente.nome, paciente.idade, paciente.CPF, paciente.email, paciente.senha, paciente.CEP))
        self.conn.commit()

    def listarPacientes(self):
        self.cursor.execute("SELECT id, nome, idade,  cpf, email, senha, cep FROM PACIENTE")
        rows = self.cursor.fetchall()
        return [Paciente(id=row[0], nome=row[1], idade=row[2], CPF=row[3], email=row[4], senha=row[5], CEP=row[6]) for row in rows]

    def atualizarPaciente(self, paciente_id, novoNome, novaIdade, novoEmail, novaSenha, novoCEP):
        sql = "UPDATE PACIENTE SET nome = :1, idade = :2, email = :3, senha = :4, cep = :5 WHERE id = :6"
        self.cursor.execute(sql, (novoNome, novaIdade, novoEmail, novaSenha, novoCEP, paciente_id))
        self.conn.commit()

    def deletarPaciente(self, paciente_id):
        sql = "DELETE FROM PACIENTE WHERE id = :1"
        self.cursor.execute(sql, (paciente_id,))
        self.conn.commit()