from models.pacienteModel import Paciente

class pacienteCRUD:
    def __init__(self, conexao):
        self.conn = conexao
        self.cursor = self.conn.cursor()

    def criarTabelaPaciente(self):
        self.cursor.execute("""
            CREATE TABLE pacientes (
                id NUMBER (8) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome VARCHAR2(100) NOT NULL,
                idade NUMBER (3) NOT NULL,
                CPF VARCHAR2(20) NOT NULL
            )
        """)
        self.conn.commit()

    def criarPaciente (self, paciente: Paciente):
        sql = "INSERT INTO paciente (nome, idade, cpf) VALUE ( :1, :2, :3)"
        self.cursor.execute(sql, (paciente.nome, paciente.idade, paciente.cpf))
        self.conn.commit()

    def listarPacientes(self):
        self.cursor.execute("SELECT id, nome, cpf FROM paciente")
        rows = self.cursor.fetchall()
        return [Paciente(nome = row[1], idade=row[2], cpf=row[3]) for row in rows]
    
    def atualizarPaciente(self, paciente_id, novoNome, novaIdade):
        sql = "UPDATE paciente SET nome = :1, idade = :2 WHERE id = :3"
        self.cursor.execute(sql, (novoNome, novaIdade, paciente_id))
        self.conn.commit()

    def deletarPaciente(self, paciente_id):
        sql = "DELETE FROM paciente WHERE id = :1"
        self.cursor.execute(sql, (paciente_id,))
        self.conn.commit()